### ISSUE TITLE
无法打开url

### ISSUE THREAD

**Issue by 0x1a551e2** [Maklith/Kitopia-issues#1]
![I)VX_VDFA7@ }UW1I)}PQ4I](https://github.com/MakesYT/Kitopia-issues/assets/104710863/77e16d14-d51a-4e26-9a58-052e494b9aa8)
![Q_H_A96ZTX_HCJ07A)0UVW3](https://github.com/MakesYT/Kitopia-issues/assets/104710863/1491589e-ad02-4520-8c8c-ea923f693689)
![image](https://github.com/MakesYT/Kitopia-issues/assets/104710863/b2f80a53-6ab6-4188-a473-be48f664bf1c)
搜索带有“/”或“\”的非文件路径字符串不会返回任何结果

**Comment by Maklith** [comment]
已修复,同时优化打开网页的排序

**Comment by Maklith** [comment]
修复无法打开url(带有“/”或“\”的非文件路径字符串不会返回任何结果)
优化打开网页排序
修复数学计算无法计算小数
