### ISSUE TITLE
快捷键功能异常

### ISSUE THREAD

**Issue by 0x1a551e2** [Maklith/Kitopia-issues#2]
![image](https://github.com/MakesYT/Kitopia-issues/assets/104710863/837e1458-386c-4271-b4b6-9c1d51631f96)
1.名字显示不正常，如图为将快捷键设置为ctrl+小键盘0

![image](https://github.com/MakesYT/Kitopia-issues/assets/104710863/9e89cf0c-a451-4f4d-bd1d-a19e05561f3b)
2.设置后显示错误，图中设置的依旧是ctrl+小键盘0，可以用ctrl+小键盘0唤起搜索框，但显示不对

![image](https://github.com/MakesYT/Kitopia-issues/assets/104710863/44b33ab4-cbbb-488d-a6a9-7a7d3355b1d5)
3.在上一条之后再次点进设置快捷键界面，再次将快捷键设置为无法正常识别的组合，则会导致软件彻底无法运行

**Comment by Maklith** [comment]
修改注册快捷键逻辑,允许在注册失败时重新设置,补全按键映射表
修复仅有Ctrl键时显示bug
