### ISSUE TITLE
计算器int太容易溢出

### ISSUE THREAD

**Issue by 0x1a551e2** [Maklith/Kitopia-issues#4]
![I8_~W(@@Q}4_Q4NGNC`NZFI](https://github.com/MakesYT/Kitopia-issues/assets/104710863/782b07ac-8ec0-4031-83e6-0d7484405da9)
![X6}7_DJAF)754~A)A4 1_5I](https://github.com/MakesYT/Kitopia-issues/assets/104710863/e5006aca-6e52-4ff3-a173-d5b02bd01e9f)

**Comment by Maklith** [comment]
修复部分溢出,但不会完全修复这只是一个简便计算器不应该用来完全当计算器使用
(主要是要自己写解析不想弄)
