### ISSUE TITLE
快捷键设置bug

### ISSUE THREAD

**Issue by 0x1a551e2** [Maklith/Kitopia-issues#6]
在快捷键设置界面只按一个键（比如a）会显示空白
![image](https://github.com/MakesYT/Kitopia-issues/assets/104710863/6beff040-3dd2-4948-9f50-09275f964e89)
保存后功能出现异常，与https://github.com/MakesYT/Kitopia-issues/issues/2类似

**Comment by Maklith** [comment]
现已允许单按键作为快捷键激活,并修复显示bug
