### ISSUE TITLE
输入平滑延时修改后不会保存

### ISSUE THREAD

**Issue by 0x1a551e2** [Maklith/Kitopia-issues#8]
![image](https://github.com/MakesYT/Kitopia-issues/assets/104710863/80c74c48-5e0a-412d-a631-d9b0263ae3fe)
好像本来就没有保存按钮，其他属性修改后切换到其他地方再切回来可以保存，只有这个不行

**Comment by Maklith** [comment]
已解决,这是一个显示错误,实际上已保存
