### ISSUE TITLE
窗口最大化时出现渲染错误

### ISSUE THREAD

**Issue by 0x1a551e2** [Maklith/Kitopia-issues#9]
拖动窗口到屏幕顶端最大化会导致渲染错误
双击或点击右上角按钮放大不会出错
![06VPULO4V59U 7L}@H9ZH%G](https://github.com/MakesYT/Kitopia-issues/assets/104710863/33b6ade5-ddd1-4e0f-8a9d-a3c25d99fa2c)
![8{A73KZ`$AI{F%DF IY6FDL](https://github.com/MakesYT/Kitopia-issues/assets/104710863/b1291b45-c37a-4ef4-9fea-7bde5af02905)

**Comment by Maklith** [comment]
无法复现
